name: E2E Tests

on:
  push:
    branches:
      - '**' #zabezpieczyc zeby na developie sie nie odpalalo
      - '!develop'
  pull_request:
    branches:
      - '**'  

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ping:1})'" 
          --health-interval 10s 
          --health-timeout 10s 
          --health-retries 5
        

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm ci

    - name: Check MongoDB logs
      run: docker logs $(docker ps -aqf "name=mongo")

    - name: Wait for MongoDB to be ready
      run: |
        until docker exec mongodb-container mongo --eval "db.adminCommand('ping')"; do
          echo "Waiting for MongoDB to initialize..."
          sleep 20
        done

    - name: Check MongoDB logs
      run: docker logs <nazwa_kontenera_mongo>

    - name: Run e2e tests
      env:
       MONGODB_HOST: localhost
       MONGODB_PORT: 27017
       MONGODB_DATABASE: dev
       MONGODB_USER: root
       MONGODB_PASSWORD: dev
       MONGO_URI: mongodb://localhost:4455/api/v1
      run: npm run test:e2e
