name: E2E Tests

on:
  push:
    branches:
      - '**'
      - '!develop'
  pull_request:
    branches:
      - '**'  

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0  # Użyj konkretnej wersji MongoDB
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ping:1})'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install

    - name: Wait for MongoDB
      run: sleep 30  

    - name: Run e2e tests
      env:
        MONGO_URI: mongodb://localhost:27017/test-db
      run: npm run test:e2e

    - name: Check MongoDB logs  # Debugowanie
      run: docker logs <nazwa_kontenera_mongo>  # Uzupełnij nazwę kontenera
